### ISSUE TITLE
App crashes "AURGA Viewer has stopped" on Android 8.1

### ISSUE THREAD

**Issue by static-void** [aurgatech/issues#2]
I am attaching logcat info.
[logs-2023-11-03-13-32-29.zip](https://github.com/aurgatech/issues/files/13250758/logs-2023-11-03-13-32-29.zip)

**Comment by aurgatech** [comment]
@static-void The bug is fixed. Please download the latest app from Play Store or the download page.

**Comment by static-void** [comment]
I have tested it and it works. I am very impressed by this level of support, thank you!
